name: (scheduled) create html
on: 
  schedule: 
    - cron: '00 * * * *' 
    # runs every hour
    # minute(0-59) / hour(0-23) / day of month(1-31) / month(1-12) / day of week(0-6)
jobs:
  deploy:
    name: First job
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Disable Python cache
        run: export PYTHONDONTWRITEBYTECODE=1
      - name: check for updates
        run: python3 .github/src/check_updates.py
      - name: create plugins
        run: python3 .github/src/create_plugins.py
      - name: delete downloaded files
        run: python3 .github/src/delete_downloaded.py
      - name: Commit file
        run: |
          git config user.name "script" 
          git config user.email "woot@woot.com"
          git add "plugins/"
          git diff-index --quiet HEAD || git commit -m "new version"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
